apiVersion: v1
kind: Service
metadata:
  name: netology-service
spec:
  ports:
    - name: web-nginx
      port: 9001
      targetPort: 80
    - name: web-multitools
      port: 9002
      targetPort: 8080
  selector:
    app: main