apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    app: main2
spec:
  containers:
    - name: app-busybox
      image: busybox
      command: ['sh', '-c', 'while true; do echo Success! >> /input/success.txt; sleep 5; done']
      volumeMounts:
      - name: vol
        mountPath: /input
    - name: network-multitool
      image: wbitt/network-multitool
      volumeMounts:
      - name: vol
        mountPath: /output
  volumes:
  - name: vol
    hostPath:
      path: /var/data
